scalar Date

type News {
    id: String
    title: String
    content: String
    user: User
    createdAt: Date
    updatedAt: Date
}

type User {
    id: String
    name: String
    email: String
    password: String
    news: [News]
    createdAt: Date
    updatedAt: Date
}

type Query {
    users: [User]!
}

input userInput {
    name: String
    email: String
    password: String
}

input sessionInput {
    email: String
    password: String
}

type Session {
    token: String
    user: User
}

type Mutation {
    createUser(user: userInput): User
    createSession(data: sessionInput): Session
}